### ISSUE TITLE
[Feature]: Add A Tabs Panel In Profile Page To Switch Between All Posts and Collaborative Posts.

### ISSUE THREAD

**Issue by piyusharmap** [the-monkeys/the_monkeys#167]
### 🔰 Type of Feature:

- [x] 💡 Feature
- [ ] 🐛 Bug Fix
- [ ] 📃 Documentation
- [ ] 🎨 Style
- [ ] 💻 Code Refactor
- [ ] 🔥 Performance
- [ ] ✅ Test

### ❓ Is your feature request related to a problem? Please describe.

NIL

### 📃 Describe the solution you'd like.

To achieve this feature, we need a Tabs Panel that we can use to switch between all posts and collaborative posts. For this, we can use the Shadcn Tabs component. The required tasks are:

1. Remove the existing link to the activity page from the profile section.
2. Add the Shadcn component to render tabs to switch between 'All' and 'Collab'.
3. Use some mock data as tab content to show the working of the tabs.

### 📃 Describe alternatives you've considered.

NIL

### 👂 Additional context

Use below image as reference:
![image](https://github.com/the-monkeys/the_monkeys/assets/75241694/873c5953-57b1-4fe5-8d39-34c55e5fc4cf)

**Comment by obere4u** [comment]
I have done this, take a look at what I did and tell me what color I should use on the hover state and if there are any correction before I make a PR
![Screenshot (9)](https://github.com/the-monkeys/the_monkeys/assets/54867289/efe4734f-bbdb-4dad-9335-cb65f83426ec)
.

**Comment by binary-best** [comment]
@piyusharmap please help @obere4u with the design

**Comment by piyusharmap** [comment]
@obere4u There are some changes in the design, and now we will be showing a tab switch between all posts and collaborative posts. Please refer to the changes in the issue and design the tabs panel accordingly. 
For now, you can just use the base Shadcn component to render the tabs.

Shadcn Tabs: https://ui.shadcn.com/docs/components/tabs

**Comment by obere4u** [comment]
> @obere4u There are some changes in the design, and now we will be showing a tab switch between all posts and collaborative posts. Please refer to the changes in the issue and design the tabs panel accordingly. For now, you can just use the base Shadcn component to render the tabs.
> 
> Shadcn Tabs: https://ui.shadcn.com/docs/components/tabs

![Screenshot (10)](https://github.com/the-monkeys/the_monkeys/assets/54867289/7c6719bf-8e5e-4fb0-a3ae-68bcc1aa0056)
This is the code of what I did.

**Comment by binary-best** [comment]
@obere4u basic tab switch is ok, go ahead and raise the PR, we will comment incase we require any change.

**Comment by obere4u** [comment]
When I click on the All Post, how will the page look like, same with Collab @piyusharmap

**Comment by piyusharmap** [comment]
A list of blog posts related to current tab. But for now, just add a placeholder stating that the list is currently empty.
