### ISSUE TITLE
[Bug]: Closing Publish Modal Redirects To Previous URL

### ISSUE THREAD

**Issue by piyusharmap** [the-monkeys/the_monkeys#179]
### 🐛 Describe the bug:

The close button in the modal has the functionality to redirect the user to the last visited URL. This functionality works fine with auth modals, but due to this, when we close the publish modal, we are redirected to the previous URL, which is not suitable for a good user experience.

### 🔃 Steps To Reproduce

1. Go to the settings page.
2. Go to the create page.
3. Click on the Publish button; a publish modal will open.
4. When we close this modal, we will be redirected to the settings page.

### 📃 Expected behavior

When we close the modal, the user should stay on the create page.

### 📸 Screenshots

NIL

### 👂 Additional context

NIL

**Comment by obere4u** [comment]
@piyusharmap If I understand this very well, the [x] on the model, when clicked will reroute the page to a previous route, right? because when I checked the code, I saw that `router.back()` is making the page go back to the previous route instead of only setting the `setModal(false)`
