### ISSUE TITLE
[Bug]: Error Popup In Reset Password Page If Token Is Invalid

### ISSUE THREAD

**Issue by piyusharmap** [the-monkeys/the_monkeys#186]
### 🐛 Describe the bug:

When we are redirected to the reset password page, the reset password form is still available even if the authentication token is invalid. 

### 🔃 Steps To Reproduce

1. Request a password reset.
2. Follow the link provided in the email.
3. The email link will redirect to the reset password page.
4. If the verification token is not valid, the password fields are still accessible.

### 📃 Expected behavior

A message should pop up to indicate that the provided authentication token is invalid.

### 📸 Screenshots

NIL

### 👂 Additional context

NIL

**Comment by SandipGyawali** [comment]
can i get to look at it ??

**Comment by piyusharmap** [comment]
@SandipGyawali yaa sure

**Comment by piyusharmap** [comment]
@SandipGyawali any update on this?

**Comment by rahulsingh3526** [comment]
can some explain to me where is the deployed project. Is everything inside the local host? how do i check the rest password and other things

**Comment by Rahullokare** [comment]
this is the deployed project repository you can check it here https://themonkeys.live/ 
in the app directory there is folder name auth/reset-password you can check there
