### ISSUE TITLE
[Feature]: Improve Input Fields For Passwords

### ISSUE THREAD

**Issue by piyusharmap** [the-monkeys/the_monkeys#192]
### 🔰 Type of Feature:

- [x] 💡 Feature
- [ ] 🐛 Bug Fix
- [ ] 📃 Documentation
- [x] 🎨 Style
- [ ] 💻 Code Refactor
- [ ] 🔥 Performance
- [ ] ✅ Test

### ❓ Is your feature request related to a problem? Please describe.

Currently, there is no way for users to see the password they have entered in the input field. There should be a way to allow users to show the password.

### 📃 Describe the solution you'd like.

To achieve this, you can either add an eye button in the input component itself or add a checkbox below the input component to show the password.

### 📃 Describe alternatives you've considered.

NIL

### 👂 Additional context

NIL

**Comment by SeanAverS** [comment]
Hello, 

I am interested on working on this. Could I please be assigned? Thank you.

**Comment by daveaugustus** [comment]
@SeanAverS please go ahead and pick this up.

**Comment by piyusharmap** [comment]
@SeanAverS, make sure to create a separate component that allows us to utilize both the existing component and the additional functionality of showing/hiding the password.
