### ISSUE TITLE
Design the settigns page

### ISSUE THREAD

**Issue by daveaugustus** [the-monkeys/the_monkeys#66]

**Comment by daveaugustus** [comment]
![Image](https://github.com/the-monkeys/the_monkeys/assets/36985548/62fa6898-485a-49d8-8e85-9b0d38c9e74b)


@arit98 and @Gourav078  here I have added a referance design for your referance

**Comment by ParthasarathiMahana** [comment]
Hi @daveaugustus Can I work on this?

**Comment by daveaugustus** [comment]
@ParthasarathiMahana you can pick up some other issue, we have delayed it due to the new design.
