### ISSUE TITLE
[Feature]: Design Forgot Password Page

### ISSUE THREAD

**Issue by daveaugustus** [the-monkeys/the_monkeys#70]
Required Tasks:

- [ ] Create a new route, /auth/forgot-password, to serve the forgot password page.
- [ ] For the page layout, take reference from the existing settings and notifications pages.
- [ ] Design the page similar to the design mentioned below.
- [ ] Provide styling that caters to both Light and Dark themes accordingly.

The image below is just for reference; the original design may differ from it.
![Forgot Password_ Dark Mode](https://github.com/the-monkeys/the_monkeys/assets/75241694/5af8a36c-9677-47c1-b8ca-5ade3f1088ee)
![Forgot Password_ Light Mode](https://github.com/the-monkeys/the_monkeys/assets/75241694/f132cfce-42a0-4595-aa58-6af1a9e8ea12)

**Comment by daveaugustus** [comment]
@piyusharmap @Rahullokare if this is done can we close it?

**Comment by piyusharmap** [comment]
No, it's not done
