### ISSUE TITLE
[Feature]: Design Reset Password Page

### ISSUE THREAD

**Issue by daveaugustus** [the-monkeys/the_monkeys#71]
**Required Tasks:**

- [ ] Create a new route, /auth/reset-password, to serve the reset password page.
- [ ] For the page layout, take reference from the existing settings and notifications pages.
- [ ] Design the page similar to the design mentioned below.
- [ ] Provide styling that caters to both Light and Dark themes accordingly.

The image below is just for reference; the original design may differ from it.
![Reset Password_ Dark Mode](https://github.com/the-monkeys/the_monkeys/assets/75241694/f3006fd8-2faf-487c-a44c-60570423883e)
![Reset Password_ Light Mode](https://github.com/the-monkeys/the_monkeys/assets/75241694/bc2c7003-c72f-458e-9ee8-c2adbf9a4d21)

**Comment by obere4u** [comment]
Is anyone doing this? I just got a new PC. Now I can fully contribute

**Comment by daveaugustus** [comment]
@obere4u you need to speak with @piyusharmap as the design has been changed

**Comment by obere4u** [comment]
Okay. I will chat him up
