### ISSUE TITLE
Redesign Profile page

### ISSUE THREAD

**Issue by daveaugustus** [the-monkeys/the_monkeys#81]
- The current profile looks extremly odd based on the theme and color.
- Redesing the profile and make theme suitable
- Default profile pic is a monkey pic

![Image](https://github.com/the-monkeys/the_monkeys/assets/36985548/7d6edfe9-3123-4ff2-b728-731fa7a12a26)

**Comment by tarun0306** [comment]
![image](https://github.com/the-monkeys/the_monkeys/assets/98694423/d763ae39-60b4-411b-b901-0f1797f6d5b0)
![image](https://github.com/the-monkeys/the_monkeys/assets/98694423/5a3c0e6a-fba7-4cff-928d-3cc1251e8226)

As you can see the API getting status 500 so i think that's the reason the profile pic looks weird 
in the code also we can see the API call is being made so it's not null and going through

**Comment by daveaugustus** [comment]
@tarun0306 this issue has been fixed and merged to main and @Yash3456 is continuing with this feature...
