### ISSUE TITLE
Write Page "Cookie policy" (Footer)

### ISSUE THREAD

**Issue by daveaugustus** [the-monkeys/the_monkeys#96]
# Cookie Policy for The Monkeys

## What Are Cookies

Cookies are small text files that are placed on your computer by websites that you visit. They are widely used in order to make websites work, or work more efficiently, as well as to provide information to the owners of the site.

## How We Use Cookies

We use cookies for a variety of reasons detailed below. Unfortunately, in most cases, there are no industry standard options for disabling cookies without completely disabling the functionality and features they add to this site.

## Disabling Cookies

You can prevent the setting of cookies by adjusting the settings on your browser. Be aware that disabling cookies will affect the functionality of this and many other websites that you visit.

## The Cookies We Set

- Account related cookies: If you create an account with us then we will use cookies for the management of the signup process and general administration.
- Email newsletters related cookies: This site offers newsletter or email subscription services and cookies may be used to remember if you are already registered and whether to show certain notifications which might only be valid to subscribed/unsubscribed users.

## More Information

If you are looking for more information then you can contact us through one of our preferred contact methods.

_Last updated: (insert date)_

**Comment by sumitavachakraborty** [comment]
created the pull request, kindly do a review
